# Generated by Django 3.1.2 on 2021-01-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
